name: qrcode_reader

description: Flutter plugin that lets you read a QR Code.
author: Matheus Villela <matheusvillela@gmail.com>
homepage: https://github.com/villela/flutter_qrcode_reader
version: 0.5.0

flutter:
  plugin:
    androidPackage: com.matheusvillela.flutter.plugins.qrcodereader
    pluginClass: QRCodeReaderPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
